// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vaporchain/council/v1/council.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params governs validator admission and the emergency guardian role.
type Params struct {
	// guardians may PAUSE Settle / IBC denoms. They cannot move funds, cannot
	// unpause and their pauses expire after guardian_pause_max_blocks.
	Guardians []string `protobuf:"bytes,1,rep,name=guardians,proto3" json:"guardians,omitempty"`
	// guardian_pause_max_blocks bounds a guardian-initiated pause so that a
	// compromised guardian key cannot halt payments forever.
	GuardianPauseMaxBlocks uint64 `protobuf:"varint,2,opt,name=guardian_pause_max_blocks,json=guardianPauseMaxBlocks,proto3" json:"guardian_pause_max_blocks,omitempty"`
	// max_power_per_validator caps a single admission grant (base units of
	// avpower) so one proposal cannot hand a single operator > 1/3 power.
	MaxPowerPerValidator cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=max_power_per_validator,json=maxPowerPerValidator,proto3,customtype=cosmossdk.io/math.Int" json:"max_power_per_validator"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bd75303579ebd0, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetGuardians() []string {
	if m != nil {
		return m.Guardians
	}
	return nil
}

func (m *Params) GetGuardianPauseMaxBlocks() uint64 {
	if m != nil {
		return m.GuardianPauseMaxBlocks
	}
	return 0
}

// Admission records an operator allowed to run a validator.
type Admission struct {
	Operator       string                `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	PowerGranted   cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=power_granted,json=powerGranted,proto3,customtype=cosmossdk.io/math.Int" json:"power_granted"`
	AdmittedHeight int64                 `protobuf:"varint,3,opt,name=admitted_height,json=admittedHeight,proto3" json:"admitted_height,omitempty"`
	// removed operators can never create a validator again.
	Removed bool   `protobuf:"varint,4,opt,name=removed,proto3" json:"removed,omitempty"`
	Memo    string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *Admission) Reset()         { *m = Admission{} }
func (m *Admission) String() string { return proto.CompactTextString(m) }
func (*Admission) ProtoMessage()    {}
func (*Admission) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bd75303579ebd0, []int{1}
}
func (m *Admission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Admission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Admission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Admission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admission.Merge(m, src)
}
func (m *Admission) XXX_Size() int {
	return m.Size()
}
func (m *Admission) XXX_DiscardUnknown() {
	xxx_messageInfo_Admission.DiscardUnknown(m)
}

var xxx_messageInfo_Admission proto.InternalMessageInfo

func (m *Admission) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Admission) GetAdmittedHeight() int64 {
	if m != nil {
		return m.AdmittedHeight
	}
	return 0
}

func (m *Admission) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Admission) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// Pause is an emergency stop on a target. Targets:
//
//	"settle"           every Settle payment
//	"settle:<denom>"   Settle payments in one asset
//	"ibc"              every outbound/inbound ICS-20 transfer
//	"ibc:<denom>"      ICS-20 transfers of one base denom
type Pause struct {
	Target    string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	SetBy     string `protobuf:"bytes,2,opt,name=set_by,json=setBy,proto3" json:"set_by,omitempty"`
	SetHeight int64  `protobuf:"varint,3,opt,name=set_height,json=setHeight,proto3" json:"set_height,omitempty"`
	// expires_height == 0 means "until governance unpauses".
	ExpiresHeight int64  `protobuf:"varint,4,opt,name=expires_height,json=expiresHeight,proto3" json:"expires_height,omitempty"`
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *Pause) Reset()         { *m = Pause{} }
func (m *Pause) String() string { return proto.CompactTextString(m) }
func (*Pause) ProtoMessage()    {}
func (*Pause) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bd75303579ebd0, []int{2}
}
func (m *Pause) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pause.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pause.Merge(m, src)
}
func (m *Pause) XXX_Size() int {
	return m.Size()
}
func (m *Pause) XXX_DiscardUnknown() {
	xxx_messageInfo_Pause.DiscardUnknown(m)
}

var xxx_messageInfo_Pause proto.InternalMessageInfo

func (m *Pause) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Pause) GetSetBy() string {
	if m != nil {
		return m.SetBy
	}
	return ""
}

func (m *Pause) GetSetHeight() int64 {
	if m != nil {
		return m.SetHeight
	}
	return 0
}

func (m *Pause) GetExpiresHeight() int64 {
	if m != nil {
		return m.ExpiresHeight
	}
	return 0
}

func (m *Pause) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// Provenance is written once at genesis and can never be modified by any
// message. It is the on-chain authorship record of VaporChain.
type Provenance struct {
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Seal        string `protobuf:"bytes,2,opt,name=seal,proto3" json:"seal,omitempty"`
	Owner       string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Notice      string `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
}

func (m *Provenance) Reset()         { *m = Provenance{} }
func (m *Provenance) String() string { return proto.CompactTextString(m) }
func (*Provenance) ProtoMessage()    {}
func (*Provenance) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bd75303579ebd0, []int{3}
}
func (m *Provenance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Provenance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Provenance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Provenance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provenance.Merge(m, src)
}
func (m *Provenance) XXX_Size() int {
	return m.Size()
}
func (m *Provenance) XXX_DiscardUnknown() {
	xxx_messageInfo_Provenance.DiscardUnknown(m)
}

var xxx_messageInfo_Provenance proto.InternalMessageInfo

func (m *Provenance) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *Provenance) GetSeal() string {
	if m != nil {
		return m.Seal
	}
	return ""
}

func (m *Provenance) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Provenance) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

// GenesisState of x/council.
type GenesisState struct {
	Params     Params      `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Admissions []Admission `protobuf:"bytes,2,rep,name=admissions,proto3" json:"admissions"`
	Pauses     []Pause     `protobuf:"bytes,3,rep,name=pauses,proto3" json:"pauses"`
	Provenance Provenance  `protobuf:"bytes,4,opt,name=provenance,proto3" json:"provenance"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bd75303579ebd0, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetAdmissions() []Admission {
	if m != nil {
		return m.Admissions
	}
	return nil
}

func (m *GenesisState) GetPauses() []Pause {
	if m != nil {
		return m.Pauses
	}
	return nil
}

func (m *GenesisState) GetProvenance() Provenance {
	if m != nil {
		return m.Provenance
	}
	return Provenance{}
}

func init() {
	proto.RegisterType((*Params)(nil), "vaporchain.council.v1.Params")
	proto.RegisterType((*Admission)(nil), "vaporchain.council.v1.Admission")
	proto.RegisterType((*Pause)(nil), "vaporchain.council.v1.Pause")
	proto.RegisterType((*Provenance)(nil), "vaporchain.council.v1.Provenance")
	proto.RegisterType((*GenesisState)(nil), "vaporchain.council.v1.GenesisState")
}

func init() {
	proto.RegisterFile("vaporchain/council/v1/council.proto", fileDescriptor_24bd75303579ebd0)
}

var fileDescriptor_24bd75303579ebd0 = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x4f, 0xdb, 0x48,
	0x14, 0x8f, 0xc9, 0x9f, 0x25, 0x13, 0x60, 0xb5, 0xa3, 0x90, 0x35, 0xec, 0x12, 0xb2, 0x59, 0xad,
	0x36, 0x62, 0x45, 0xbc, 0x64, 0x57, 0x48, 0xe5, 0x54, 0x72, 0x28, 0xe5, 0x50, 0x29, 0x32, 0x52,
	0x0f, 0xbd, 0x58, 0x13, 0xfb, 0xd5, 0x19, 0x11, 0xcf, 0x58, 0x33, 0xe3, 0x10, 0xbe, 0x42, 0x4f,
	0x3d, 0xf4, 0xda, 0x7b, 0x8f, 0x1c, 0xf8, 0x10, 0x1c, 0x11, 0xa7, 0xaa, 0x07, 0x54, 0xc1, 0x01,
	0xa9, 0x9f, 0xa1, 0x87, 0xca, 0xe3, 0x71, 0x42, 0xa5, 0x52, 0xa9, 0x17, 0xeb, 0xfd, 0xf9, 0xbd,
	0xdf, 0xfb, 0xbd, 0xe7, 0x67, 0xa3, 0x3f, 0x27, 0x24, 0xe6, 0xc2, 0x1f, 0x11, 0xca, 0x1c, 0x9f,
	0x27, 0xcc, 0xa7, 0x63, 0x67, 0xb2, 0x93, 0x9b, 0xdd, 0x58, 0x70, 0xc5, 0xf1, 0xea, 0x1c, 0xd4,
	0xcd, 0x33, 0x93, 0x9d, 0xf5, 0x7a, 0xc8, 0x43, 0xae, 0x11, 0x4e, 0x6a, 0x65, 0xe0, 0xf5, 0x35,
	0x9f, 0xcb, 0x88, 0x4b, 0x2f, 0x4b, 0x64, 0x8e, 0x49, 0xfd, 0x42, 0x22, 0xca, 0xb8, 0xa3, 0x9f,
	0x59, 0xa8, 0xfd, 0xd9, 0x42, 0x95, 0x01, 0x11, 0x24, 0x92, 0x78, 0x17, 0x55, 0xc3, 0x84, 0x88,
	0x80, 0x12, 0x26, 0x6d, 0xab, 0x55, 0xec, 0x54, 0xfb, 0xf6, 0xd5, 0xf9, 0x76, 0xdd, 0x50, 0xec,
	0x07, 0x81, 0x00, 0x29, 0x8f, 0x94, 0xa0, 0x2c, 0x74, 0xe7, 0x50, 0xfc, 0x08, 0xad, 0xe5, 0x8e,
	0x17, 0x93, 0x44, 0x82, 0x17, 0x91, 0xa9, 0x37, 0x1c, 0x73, 0xff, 0x58, 0xda, 0x0b, 0x2d, 0xab,
	0x53, 0x72, 0x1b, 0x39, 0x60, 0x90, 0xe6, 0x9f, 0x91, 0x69, 0x5f, 0x67, 0xf1, 0x10, 0xfd, 0x9a,
	0x62, 0x63, 0x7e, 0x02, 0xc2, 0x8b, 0x41, 0x78, 0x13, 0x32, 0xa6, 0x01, 0x51, 0x5c, 0xd8, 0xc5,
	0x96, 0xd5, 0xa9, 0xf6, 0xff, 0xb9, 0xb8, 0xde, 0x2c, 0x7c, 0xb8, 0xde, 0x5c, 0xcd, 0x44, 0xc8,
	0xe0, 0xb8, 0x4b, 0xb9, 0x13, 0x11, 0x35, 0xea, 0x1e, 0x32, 0x75, 0x75, 0xbe, 0x8d, 0x8c, 0xba,
	0x43, 0xa6, 0xdc, 0x7a, 0x44, 0xa6, 0x83, 0x94, 0x6a, 0x00, 0xe2, 0x79, 0x4e, 0xb4, 0xf7, 0xdb,
	0xab, 0xbb, 0xb3, 0xad, 0x86, 0xde, 0xa0, 0x33, 0x9d, 0xed, 0x38, 0x9b, 0xb9, 0xfd, 0xc9, 0x42,
	0xd5, 0xfd, 0x20, 0xa2, 0x52, 0x52, 0xce, 0xf0, 0xff, 0x68, 0x91, 0xc7, 0x20, 0x74, 0x7f, 0xab,
	0x65, 0x7d, 0x77, 0x01, 0x33, 0x24, 0x1e, 0xa0, 0xe5, 0x6c, 0x80, 0x50, 0x10, 0xa6, 0x20, 0xb0,
	0x17, 0x7e, 0x5c, 0xfa, 0x92, 0x66, 0x38, 0xc8, 0x08, 0xf0, 0xdf, 0xe8, 0x67, 0x12, 0x44, 0x54,
	0x29, 0x08, 0xbc, 0x11, 0xd0, 0x70, 0xa4, 0xf4, 0x3a, 0x8a, 0xee, 0x4a, 0x1e, 0x7e, 0xaa, 0xa3,
	0xd8, 0x46, 0x3f, 0x09, 0x88, 0xf8, 0x04, 0x02, 0xbb, 0xd4, 0xb2, 0x3a, 0x8b, 0x6e, 0xee, 0x62,
	0x8c, 0x4a, 0x11, 0x44, 0xdc, 0x2e, 0xa7, 0x5a, 0x5c, 0x6d, 0xb7, 0xdf, 0x58, 0xa8, 0xac, 0x5f,
	0x00, 0x6e, 0xa0, 0x8a, 0x22, 0x22, 0x04, 0x95, 0x8d, 0xe9, 0x1a, 0x0f, 0xaf, 0xa2, 0x8a, 0x04,
	0xe5, 0x0d, 0x4f, 0xb3, 0x19, 0xdc, 0xb2, 0x04, 0xd5, 0x3f, 0xc5, 0x1b, 0x08, 0xa5, 0xe1, 0xaf,
	0xa4, 0x54, 0x25, 0x28, 0xa3, 0xe2, 0x2f, 0xb4, 0x02, 0xd3, 0x98, 0x0a, 0x90, 0x39, 0xa4, 0xa4,
	0x21, 0xcb, 0x26, 0x6a, 0x60, 0x0d, 0x54, 0x11, 0x40, 0x24, 0x67, 0x46, 0x94, 0xf1, 0xda, 0x31,
	0x42, 0x03, 0xc1, 0x27, 0xc0, 0x08, 0xf3, 0x01, 0xb7, 0x50, 0xed, 0x25, 0x65, 0x21, 0x88, 0x58,
	0x50, 0x96, 0xeb, 0xbb, 0x1f, 0x4a, 0x47, 0x93, 0x40, 0xc6, 0x46, 0xa2, 0xb6, 0x71, 0x1d, 0x95,
	0xf9, 0x09, 0x03, 0x73, 0x36, 0x6e, 0xe6, 0xa4, 0x1d, 0x19, 0x57, 0xd4, 0x07, 0x2d, 0xa8, 0xea,
	0x1a, 0xaf, 0xfd, 0x76, 0x01, 0x2d, 0x1d, 0x00, 0x03, 0x49, 0xe5, 0x91, 0x22, 0x0a, 0xf0, 0x63,
	0x54, 0x89, 0xf5, 0x41, 0xe8, 0x7e, 0xb5, 0xde, 0x46, 0xf7, 0x9b, 0x5f, 0x5c, 0x37, 0xbb, 0x9a,
	0x7e, 0x35, 0x7d, 0xb5, 0xef, 0xee, 0xce, 0xb6, 0x2c, 0xd7, 0xd4, 0xe1, 0x27, 0x08, 0x91, 0xfc,
	0x8e, 0xd2, 0xab, 0x2f, 0x76, 0x6a, 0xbd, 0xd6, 0x03, 0x2c, 0xb3, 0x83, 0xeb, 0x97, 0x52, 0x22,
	0xf7, 0x5e, 0x25, 0xde, 0x4b, 0x95, 0x24, 0x12, 0xa4, 0x5d, 0xd4, 0x1c, 0xbf, 0x3f, 0xa8, 0x24,
	0x91, 0x60, 0xea, 0x4d, 0x05, 0x3e, 0x40, 0x28, 0x9e, 0x2d, 0x52, 0x8f, 0x5c, 0xeb, 0xfd, 0xf1,
	0x50, 0xfd, 0x0c, 0x98, 0x8b, 0x98, 0x97, 0xf6, 0x07, 0x17, 0x37, 0x4d, 0xeb, 0xf2, 0xa6, 0x69,
	0x7d, 0xbc, 0x69, 0x5a, 0xaf, 0x6f, 0x9b, 0x85, 0xcb, 0xdb, 0x66, 0xe1, 0xfd, 0x6d, 0xb3, 0xf0,
	0x62, 0x37, 0xa4, 0x6a, 0x94, 0x0c, 0xbb, 0x3e, 0x8f, 0x9c, 0x28, 0x51, 0xa3, 0xa4, 0xd7, 0xfb,
	0x77, 0xc7, 0xd1, 0x2d, 0xb6, 0xcd, 0x4f, 0x4c, 0x3f, 0xe7, 0x1f, 0x9a, 0x3a, 0x8d, 0x41, 0x0e,
	0x2b, 0xfa, 0x6f, 0xf3, 0xdf, 0x97, 0x01, 0x00, 0xe2, 0x91, 0xab, 0xf8, 0xef, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxPowerPerValidator.Size()
		i -= size
		if _, err := m.MaxPowerPerValidator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCouncil(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.GuardianPauseMaxBlocks != 0 {
		i = encodeVarintCouncil(dAtA, i, uint64(m.GuardianPauseMaxBlocks))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Guardians) > 0 {
		for iNdEx := len(m.Guardians) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Guardians[iNdEx])
			copy(dAtA[i:], m.Guardians[iNdEx])
			i = encodeVarintCouncil(dAtA, i, uint64(len(m.Guardians[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Admission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Admission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Admission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Removed {
		i--
		if m.Removed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.AdmittedHeight != 0 {
		i = encodeVarintCouncil(dAtA, i, uint64(m.AdmittedHeight))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.PowerGranted.Size()
		i -= size
		if _, err := m.PowerGranted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCouncil(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Pause) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pause) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pause) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ExpiresHeight != 0 {
		i = encodeVarintCouncil(dAtA, i, uint64(m.ExpiresHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.SetHeight != 0 {
		i = encodeVarintCouncil(dAtA, i, uint64(m.SetHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SetBy) > 0 {
		i -= len(m.SetBy)
		copy(dAtA[i:], m.SetBy)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.SetBy)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Provenance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Provenance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Provenance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Notice) > 0 {
		i -= len(m.Notice)
		copy(dAtA[i:], m.Notice)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Notice)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Seal) > 0 {
		i -= len(m.Seal)
		copy(dAtA[i:], m.Seal)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Seal)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Fingerprint) > 0 {
		i -= len(m.Fingerprint)
		copy(dAtA[i:], m.Fingerprint)
		i = encodeVarintCouncil(dAtA, i, uint64(len(m.Fingerprint)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Provenance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCouncil(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Pauses) > 0 {
		for iNdEx := len(m.Pauses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pauses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCouncil(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Admissions) > 0 {
		for iNdEx := len(m.Admissions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Admissions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCouncil(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCouncil(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintCouncil(dAtA []byte, offset int, v uint64) int {
	offset -= sovCouncil(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Guardians) > 0 {
		for _, s := range m.Guardians {
			l = len(s)
			n += 1 + l + sovCouncil(uint64(l))
		}
	}
	if m.GuardianPauseMaxBlocks != 0 {
		n += 1 + sovCouncil(uint64(m.GuardianPauseMaxBlocks))
	}
	l = m.MaxPowerPerValidator.Size()
	n += 1 + l + sovCouncil(uint64(l))
	return n
}

func (m *Admission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	l = m.PowerGranted.Size()
	n += 1 + l + sovCouncil(uint64(l))
	if m.AdmittedHeight != 0 {
		n += 1 + sovCouncil(uint64(m.AdmittedHeight))
	}
	if m.Removed {
		n += 2
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	return n
}

func (m *Pause) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	l = len(m.SetBy)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	if m.SetHeight != 0 {
		n += 1 + sovCouncil(uint64(m.SetHeight))
	}
	if m.ExpiresHeight != 0 {
		n += 1 + sovCouncil(uint64(m.ExpiresHeight))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	return n
}

func (m *Provenance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Fingerprint)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	l = len(m.Seal)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	l = len(m.Notice)
	if l > 0 {
		n += 1 + l + sovCouncil(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovCouncil(uint64(l))
	if len(m.Admissions) > 0 {
		for _, e := range m.Admissions {
			l = e.Size()
			n += 1 + l + sovCouncil(uint64(l))
		}
	}
	if len(m.Pauses) > 0 {
		for _, e := range m.Pauses {
			l = e.Size()
			n += 1 + l + sovCouncil(uint64(l))
		}
	}
	l = m.Provenance.Size()
	n += 1 + l + sovCouncil(uint64(l))
	return n
}

func sovCouncil(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCouncil(x uint64) (n int) {
	return sovCouncil(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCouncil
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guardians", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guardians = append(m.Guardians, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardianPauseMaxBlocks", wireType)
			}
			m.GuardianPauseMaxBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GuardianPauseMaxBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPowerPerValidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxPowerPerValidator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCouncil(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCouncil
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Admission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCouncil
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Admission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Admission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerGranted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PowerGranted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdmittedHeight", wireType)
			}
			m.AdmittedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AdmittedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Removed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Removed = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCouncil(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCouncil
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Pause) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCouncil
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pause: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pause: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetHeight", wireType)
			}
			m.SetHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SetHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresHeight", wireType)
			}
			m.ExpiresHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCouncil(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCouncil
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Provenance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCouncil
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Provenance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Provenance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fingerprint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fingerprint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Notice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Notice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCouncil(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCouncil
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCouncil
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admissions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admissions = append(m.Admissions, Admission{})
			if err := m.Admissions[len(m.Admissions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pauses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pauses = append(m.Pauses, Pause{})
			if err := m.Pauses[len(m.Pauses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provenance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCouncil
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Provenance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCouncil(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCouncil
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCouncil(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCouncil
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCouncil
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCouncil
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCouncil
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCouncil
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCouncil        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCouncil          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCouncil = fmt.Errorf("proto: unexpected end of group")
)
