// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vaporchain/settle/v1/settle.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeAsset is one governance-allowlisted settlement asset. All amounts are in
// the asset's base units (e.g. micro-USDC for a 6-decimal USDC).
type FeeAsset struct {
	// denom is the bank denom (e.g. ibc/<hash> for USDC.inj). Only bank-native
	// coins are allowed so Settle never executes third-party ERC-20 code.
	Denom   string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Enabled bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// min_fee is the floor applied to payments >= micro_threshold.
	MinFee cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=min_fee,json=minFee,proto3,customtype=cosmossdk.io/math.Int" json:"min_fee"`
	// max_fee caps the fee of a single payment.
	MaxFee cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=max_fee,json=maxFee,proto3,customtype=cosmossdk.io/math.Int" json:"max_fee"`
	// micro_threshold: below it, the floor is not applied (pure percentage).
	MicroThreshold cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=micro_threshold,json=microThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"micro_threshold"`
	// tab_settle_threshold: an open tab auto-settles once it reaches this.
	TabSettleThreshold cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=tab_settle_threshold,json=tabSettleThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"tab_settle_threshold"`
	// quota_weight: sponsorship gas earned per base unit of fee.
	QuotaWeight cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=quota_weight,json=quotaWeight,proto3,customtype=cosmossdk.io/math.Int" json:"quota_weight"`
	// credit_price: acredit minted per base unit when buying gas credits with
	// this asset. Zero disables credit purchases in this asset.
	CreditPrice cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=credit_price,json=creditPrice,proto3,customtype=cosmossdk.io/math.Int" json:"credit_price"`
	// symbol and decimals are informational (SDK display).
	Symbol   string `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals uint32 `protobuf:"varint,10,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (m *FeeAsset) Reset()         { *m = FeeAsset{} }
func (m *FeeAsset) String() string { return proto.CompactTextString(m) }
func (*FeeAsset) ProtoMessage()    {}
func (*FeeAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{0}
}
func (m *FeeAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeAsset.Merge(m, src)
}
func (m *FeeAsset) XXX_Size() int {
	return m.Size()
}
func (m *FeeAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeAsset.DiscardUnknown(m)
}

var xxx_messageInfo_FeeAsset proto.InternalMessageInfo

func (m *FeeAsset) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *FeeAsset) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *FeeAsset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *FeeAsset) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

// Split is how every fee is divided. Must sum to 10_000 bps.
type Split struct {
	AppBps       uint32 `protobuf:"varint,1,opt,name=app_bps,json=appBps,proto3" json:"app_bps,omitempty"`
	ValidatorBps uint32 `protobuf:"varint,2,opt,name=validator_bps,json=validatorBps,proto3" json:"validator_bps,omitempty"`
	RelayerBps   uint32 `protobuf:"varint,3,opt,name=relayer_bps,json=relayerBps,proto3" json:"relayer_bps,omitempty"`
	TreasuryBps  uint32 `protobuf:"varint,4,opt,name=treasury_bps,json=treasuryBps,proto3" json:"treasury_bps,omitempty"`
}

func (m *Split) Reset()         { *m = Split{} }
func (m *Split) String() string { return proto.CompactTextString(m) }
func (*Split) ProtoMessage()    {}
func (*Split) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{1}
}
func (m *Split) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Split) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Split.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Split) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Split.Merge(m, src)
}
func (m *Split) XXX_Size() int {
	return m.Size()
}
func (m *Split) XXX_DiscardUnknown() {
	xxx_messageInfo_Split.DiscardUnknown(m)
}

var xxx_messageInfo_Split proto.InternalMessageInfo

func (m *Split) GetAppBps() uint32 {
	if m != nil {
		return m.AppBps
	}
	return 0
}

func (m *Split) GetValidatorBps() uint32 {
	if m != nil {
		return m.ValidatorBps
	}
	return 0
}

func (m *Split) GetRelayerBps() uint32 {
	if m != nil {
		return m.RelayerBps
	}
	return 0
}

func (m *Split) GetTreasuryBps() uint32 {
	if m != nil {
		return m.TreasuryBps
	}
	return 0
}

// Params of x/settle.
type Params struct {
	FeeBps uint32     `protobuf:"varint,1,opt,name=fee_bps,json=feeBps,proto3" json:"fee_bps,omitempty"`
	Split  Split      `protobuf:"bytes,2,opt,name=split,proto3" json:"split"`
	Assets []FeeAsset `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets"`
	// treasury_admin may withdraw from the treasury pool (e.g. a multisig).
	TreasuryAdmin string `protobuf:"bytes,4,opt,name=treasury_admin,json=treasuryAdmin,proto3" json:"treasury_admin,omitempty"`
	// relayer_admin may disburse the relayer pool, only to relayer_recipients
	// and at most relayer_payout_cap per validator_payout_interval_blocks.
	RelayerAdmin      string                                   `protobuf:"bytes,5,opt,name=relayer_admin,json=relayerAdmin,proto3" json:"relayer_admin,omitempty"`
	RelayerRecipients []string                                 `protobuf:"bytes,6,rep,name=relayer_recipients,json=relayerRecipients,proto3" json:"relayer_recipients,omitempty"`
	RelayerPayoutCap  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,7,rep,name=relayer_payout_cap,json=relayerPayoutCap,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"relayer_payout_cap"`
	// sponsored_senders are EVM addresses (0x) of bundlers whose txs form the
	// sponsored lane.
	SponsoredSenders []string `protobuf:"bytes,8,rep,name=sponsored_senders,json=sponsoredSenders,proto3" json:"sponsored_senders,omitempty"`
	// sponsored_lane_max_bps caps sponsored-lane gas as a share of block gas.
	SponsoredLaneMaxBps uint32 `protobuf:"varint,9,opt,name=sponsored_lane_max_bps,json=sponsoredLaneMaxBps,proto3" json:"sponsored_lane_max_bps,omitempty"`
	// validator_payout_interval_blocks: how often the validator pool is paid
	// out to bonded validators weighted by power x uptime.
	ValidatorPayoutIntervalBlocks int64 `protobuf:"varint,10,opt,name=validator_payout_interval_blocks,json=validatorPayoutIntervalBlocks,proto3" json:"validator_payout_interval_blocks,omitempty"`
	CreditsEnabled                bool  `protobuf:"varint,11,opt,name=credits_enabled,json=creditsEnabled,proto3" json:"credits_enabled,omitempty"`
	// max_tab_age_blocks: tabs older than this may be force-settled by anyone.
	MaxTabAgeBlocks int64 `protobuf:"varint,12,opt,name=max_tab_age_blocks,json=maxTabAgeBlocks,proto3" json:"max_tab_age_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFeeBps() uint32 {
	if m != nil {
		return m.FeeBps
	}
	return 0
}

func (m *Params) GetSplit() Split {
	if m != nil {
		return m.Split
	}
	return Split{}
}

func (m *Params) GetAssets() []FeeAsset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *Params) GetTreasuryAdmin() string {
	if m != nil {
		return m.TreasuryAdmin
	}
	return ""
}

func (m *Params) GetRelayerAdmin() string {
	if m != nil {
		return m.RelayerAdmin
	}
	return ""
}

func (m *Params) GetRelayerRecipients() []string {
	if m != nil {
		return m.RelayerRecipients
	}
	return nil
}

func (m *Params) GetRelayerPayoutCap() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.RelayerPayoutCap
	}
	return nil
}

func (m *Params) GetSponsoredSenders() []string {
	if m != nil {
		return m.SponsoredSenders
	}
	return nil
}

func (m *Params) GetSponsoredLaneMaxBps() uint32 {
	if m != nil {
		return m.SponsoredLaneMaxBps
	}
	return 0
}

func (m *Params) GetValidatorPayoutIntervalBlocks() int64 {
	if m != nil {
		return m.ValidatorPayoutIntervalBlocks
	}
	return 0
}

func (m *Params) GetCreditsEnabled() bool {
	if m != nil {
		return m.CreditsEnabled
	}
	return false
}

func (m *Params) GetMaxTabAgeBlocks() int64 {
	if m != nil {
		return m.MaxTabAgeBlocks
	}
	return 0
}

// Tab is an escrowed micro-payment session.
type Tab struct {
	AppId        uint64                `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Payer        string                `protobuf:"bytes,2,opt,name=payer,proto3" json:"payer,omitempty"`
	Payee        string                `protobuf:"bytes,3,opt,name=payee,proto3" json:"payee,omitempty"`
	Denom        string                `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount       cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	OpenedHeight int64                 `protobuf:"varint,6,opt,name=opened_height,json=openedHeight,proto3" json:"opened_height,omitempty"`
	Entries      uint64                `protobuf:"varint,7,opt,name=entries,proto3" json:"entries,omitempty"`
}

func (m *Tab) Reset()         { *m = Tab{} }
func (m *Tab) String() string { return proto.CompactTextString(m) }
func (*Tab) ProtoMessage()    {}
func (*Tab) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{3}
}
func (m *Tab) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tab.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tab.Merge(m, src)
}
func (m *Tab) XXX_Size() int {
	return m.Size()
}
func (m *Tab) XXX_DiscardUnknown() {
	xxx_messageInfo_Tab.DiscardUnknown(m)
}

var xxx_messageInfo_Tab proto.InternalMessageInfo

func (m *Tab) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *Tab) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *Tab) GetPayee() string {
	if m != nil {
		return m.Payee
	}
	return ""
}

func (m *Tab) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Tab) GetOpenedHeight() int64 {
	if m != nil {
		return m.OpenedHeight
	}
	return 0
}

func (m *Tab) GetEntries() uint64 {
	if m != nil {
		return m.Entries
	}
	return 0
}

// AppAllowance lets `owner` authorize one app to pull up to `amount`.
type AppAllowance struct {
	Owner  string                `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	AppId  uint64                `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Denom  string                `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *AppAllowance) Reset()         { *m = AppAllowance{} }
func (m *AppAllowance) String() string { return proto.CompactTextString(m) }
func (*AppAllowance) ProtoMessage()    {}
func (*AppAllowance) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{4}
}
func (m *AppAllowance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppAllowance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AppAllowance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AppAllowance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppAllowance.Merge(m, src)
}
func (m *AppAllowance) XXX_Size() int {
	return m.Size()
}
func (m *AppAllowance) XXX_DiscardUnknown() {
	xxx_messageInfo_AppAllowance.DiscardUnknown(m)
}

var xxx_messageInfo_AppAllowance proto.InternalMessageInfo

func (m *AppAllowance) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AppAllowance) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AppAllowance) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// Claimable is revenue owed to an app.
type Claimable struct {
	AppId  uint64                `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Denom  string                `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *Claimable) Reset()         { *m = Claimable{} }
func (m *Claimable) String() string { return proto.CompactTextString(m) }
func (*Claimable) ProtoMessage()    {}
func (*Claimable) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{5}
}
func (m *Claimable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Claimable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Claimable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Claimable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claimable.Merge(m, src)
}
func (m *Claimable) XXX_Size() int {
	return m.Size()
}
func (m *Claimable) XXX_DiscardUnknown() {
	xxx_messageInfo_Claimable.DiscardUnknown(m)
}

var xxx_messageInfo_Claimable proto.InternalMessageInfo

func (m *Claimable) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *Claimable) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// PoolBalance is an internal ledger entry of a protocol pool.
type PoolBalance struct {
	// pool is one of "validator", "relayer", "treasury".
	Pool   string                `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Denom  string                `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *PoolBalance) Reset()         { *m = PoolBalance{} }
func (m *PoolBalance) String() string { return proto.CompactTextString(m) }
func (*PoolBalance) ProtoMessage()    {}
func (*PoolBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{6}
}
func (m *PoolBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolBalance.Merge(m, src)
}
func (m *PoolBalance) XXX_Size() int {
	return m.Size()
}
func (m *PoolBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolBalance.DiscardUnknown(m)
}

var xxx_messageInfo_PoolBalance proto.InternalMessageInfo

func (m *PoolBalance) GetPool() string {
	if m != nil {
		return m.Pool
	}
	return ""
}

func (m *PoolBalance) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// Totals are lifetime counters per denom, used by invariants and analytics.
type Totals struct {
	Denom    string                `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Volume   cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=volume,proto3,customtype=cosmossdk.io/math.Int" json:"volume"`
	Fees     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=fees,proto3,customtype=cosmossdk.io/math.Int" json:"fees"`
	Payments uint64                `protobuf:"varint,4,opt,name=payments,proto3" json:"payments,omitempty"`
}

func (m *Totals) Reset()         { *m = Totals{} }
func (m *Totals) String() string { return proto.CompactTextString(m) }
func (*Totals) ProtoMessage()    {}
func (*Totals) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{7}
}
func (m *Totals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Totals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Totals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Totals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Totals.Merge(m, src)
}
func (m *Totals) XXX_Size() int {
	return m.Size()
}
func (m *Totals) XXX_DiscardUnknown() {
	xxx_messageInfo_Totals.DiscardUnknown(m)
}

var xxx_messageInfo_Totals proto.InternalMessageInfo

func (m *Totals) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Totals) GetPayments() uint64 {
	if m != nil {
		return m.Payments
	}
	return 0
}

// GenesisState of x/settle.
type GenesisState struct {
	Params                  Params                                   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Claimables              []Claimable                              `protobuf:"bytes,2,rep,name=claimables,proto3" json:"claimables"`
	Pools                   []PoolBalance                            `protobuf:"bytes,3,rep,name=pools,proto3" json:"pools"`
	Tabs                    []Tab                                    `protobuf:"bytes,4,rep,name=tabs,proto3" json:"tabs"`
	Allowances              []AppAllowance                           `protobuf:"bytes,5,rep,name=allowances,proto3" json:"allowances"`
	Totals                  []Totals                                 `protobuf:"bytes,6,rep,name=totals,proto3" json:"totals"`
	CreditsMinted           cosmossdk_io_math.Int                    `protobuf:"bytes,7,opt,name=credits_minted,json=creditsMinted,proto3,customtype=cosmossdk.io/math.Int" json:"credits_minted"`
	RelayerPaidThisInterval github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,8,rep,name=relayer_paid_this_interval,json=relayerPaidThisInterval,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"relayer_paid_this_interval"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f05c6fb5f5c4333, []int{8}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetClaimables() []Claimable {
	if m != nil {
		return m.Claimables
	}
	return nil
}

func (m *GenesisState) GetPools() []PoolBalance {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetTabs() []Tab {
	if m != nil {
		return m.Tabs
	}
	return nil
}

func (m *GenesisState) GetAllowances() []AppAllowance {
	if m != nil {
		return m.Allowances
	}
	return nil
}

func (m *GenesisState) GetTotals() []Totals {
	if m != nil {
		return m.Totals
	}
	return nil
}

func (m *GenesisState) GetRelayerPaidThisInterval() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.RelayerPaidThisInterval
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeAsset)(nil), "vaporchain.settle.v1.FeeAsset")
	proto.RegisterType((*Split)(nil), "vaporchain.settle.v1.Split")
	proto.RegisterType((*Params)(nil), "vaporchain.settle.v1.Params")
	proto.RegisterType((*Tab)(nil), "vaporchain.settle.v1.Tab")
	proto.RegisterType((*AppAllowance)(nil), "vaporchain.settle.v1.AppAllowance")
	proto.RegisterType((*Claimable)(nil), "vaporchain.settle.v1.Claimable")
	proto.RegisterType((*PoolBalance)(nil), "vaporchain.settle.v1.PoolBalance")
	proto.RegisterType((*Totals)(nil), "vaporchain.settle.v1.Totals")
	proto.RegisterType((*GenesisState)(nil), "vaporchain.settle.v1.GenesisState")
}

func init() { proto.RegisterFile("vaporchain/settle/v1/settle.proto", fileDescriptor_3f05c6fb5f5c4333) }

var fileDescriptor_3f05c6fb5f5c4333 = []byte{
	// 1241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xcf, 0xc6, 0xeb, 0x4d, 0x3c, 0x76, 0xfa, 0x63, 0xbe, 0x69, 0xbb, 0xcd, 0xf7, 0xfb, 0x75,
	0x52, 0x23, 0x44, 0xd4, 0x2a, 0x76, 0x93, 0x0a, 0x21, 0x55, 0x20, 0x14, 0x87, 0xfe, 0x88, 0x44,
	0x21, 0xda, 0x58, 0x42, 0x42, 0x42, 0xab, 0xd9, 0xdd, 0x49, 0x3c, 0xea, 0xee, 0xce, 0xb0, 0x33,
	0x4e, 0x63, 0x09, 0xee, 0xc0, 0x89, 0x13, 0x7f, 0x03, 0x82, 0x4b, 0x0f, 0xfc, 0x01, 0x1c, 0x7b,
	0xa3, 0xe2, 0x84, 0x38, 0x14, 0x94, 0x1e, 0x7a, 0xe4, 0x5f, 0x40, 0xf3, 0x66, 0x76, 0x6d, 0x21,
	0x17, 0xa9, 0x16, 0x5c, 0x1c, 0xbf, 0x5f, 0x9f, 0xf7, 0xe6, 0xcd, 0x9b, 0xcf, 0x73, 0xd0, 0xb5,
	0x13, 0x22, 0x78, 0x11, 0x0f, 0x09, 0xcb, 0x7b, 0x92, 0x2a, 0x95, 0xd2, 0xde, 0xc9, 0xb6, 0xfd,
	0xd6, 0x15, 0x05, 0x57, 0x1c, 0xaf, 0x4e, 0x5c, 0xba, 0xd6, 0x70, 0xb2, 0xbd, 0xb6, 0x7a, 0xcc,
	0x8f, 0x39, 0x38, 0xf4, 0xf4, 0x37, 0xe3, 0xbb, 0x76, 0x35, 0xe6, 0x32, 0xe3, 0x32, 0x34, 0x06,
	0x23, 0x58, 0x53, 0xdb, 0x48, 0xbd, 0x88, 0x48, 0x9d, 0x23, 0xa2, 0x8a, 0x6c, 0xf7, 0x62, 0xce,
	0x72, 0x6b, 0xbf, 0x48, 0x32, 0x96, 0xf3, 0x1e, 0x7c, 0x1a, 0x55, 0xe7, 0x27, 0x17, 0x2d, 0xdf,
	0xa5, 0x74, 0x57, 0x4a, 0xaa, 0xf0, 0x2a, 0xaa, 0x27, 0x34, 0xe7, 0x99, 0xef, 0x6c, 0x38, 0x9b,
	0x8d, 0xc0, 0x08, 0xd8, 0x47, 0x4b, 0x34, 0x27, 0x51, 0x4a, 0x13, 0x7f, 0x71, 0xc3, 0xd9, 0x5c,
	0x0e, 0x4a, 0x11, 0xbf, 0x87, 0x96, 0x32, 0x96, 0x87, 0x47, 0x94, 0xfa, 0x35, 0x1d, 0xd1, 0xbf,
	0xf1, 0xe4, 0xd9, 0xfa, 0xc2, 0xaf, 0xcf, 0xd6, 0x2f, 0x99, 0x42, 0x64, 0xf2, 0xb0, 0xcb, 0x78,
	0x2f, 0x23, 0x6a, 0xd8, 0xdd, 0xcf, 0xd5, 0xcf, 0x3f, 0x6c, 0x21, 0x5b, 0xef, 0x7e, 0xae, 0x02,
	0x2f, 0x63, 0xf9, 0x5d, 0x4a, 0x01, 0x85, 0x9c, 0x02, 0x8a, 0x3b, 0x0f, 0x0a, 0x39, 0xd5, 0x28,
	0x03, 0x74, 0x3e, 0x63, 0x71, 0xc1, 0x43, 0x35, 0x2c, 0xa8, 0x1c, 0xf2, 0x34, 0xf1, 0xeb, 0xaf,
	0x8e, 0x76, 0x0e, 0x30, 0x06, 0x25, 0x04, 0xfe, 0x04, 0xad, 0x2a, 0x12, 0x85, 0xe6, 0x4e, 0xa6,
	0xa0, 0xbd, 0x57, 0x87, 0xc6, 0x8a, 0x44, 0x87, 0x80, 0x33, 0x81, 0xff, 0x00, 0xb5, 0x3e, 0x1d,
	0x71, 0x45, 0xc2, 0x47, 0x94, 0x1d, 0x0f, 0x95, 0xbf, 0xf4, 0xea, 0xb0, 0x4d, 0x00, 0xf8, 0x08,
	0xe2, 0x35, 0x5e, 0x5c, 0xd0, 0x84, 0xa9, 0x50, 0x14, 0x2c, 0xa6, 0xfe, 0xf2, 0x1c, 0x78, 0x06,
	0xe0, 0x40, 0xc7, 0xe3, 0xcb, 0xc8, 0x93, 0xe3, 0x2c, 0xe2, 0xa9, 0xdf, 0x80, 0x89, 0xb0, 0x12,
	0x5e, 0x43, 0xcb, 0x09, 0x8d, 0x59, 0x46, 0x52, 0xe9, 0xa3, 0x0d, 0x67, 0x73, 0x25, 0xa8, 0xe4,
	0xce, 0x97, 0x0e, 0xaa, 0x1f, 0x8a, 0x94, 0x29, 0x7c, 0x05, 0x2d, 0x11, 0x21, 0xc2, 0x48, 0x48,
	0x18, 0xa8, 0x95, 0xc0, 0x23, 0x42, 0xf4, 0x85, 0xc4, 0xaf, 0xa1, 0x95, 0x13, 0x92, 0xb2, 0x84,
	0x28, 0x5e, 0x80, 0x79, 0x11, 0xcc, 0xad, 0x4a, 0xa9, 0x9d, 0xd6, 0x51, 0xb3, 0xa0, 0x29, 0x19,
	0x53, 0xe3, 0x52, 0x03, 0x17, 0x64, 0x55, 0xda, 0xe1, 0x1a, 0x6a, 0xa9, 0x82, 0x12, 0x39, 0x2a,
	0xc6, 0xe0, 0xe1, 0x82, 0x47, 0xb3, 0xd4, 0xf5, 0x85, 0xec, 0x7c, 0x5f, 0x47, 0xde, 0x01, 0x29,
	0x48, 0x26, 0x75, 0x31, 0x47, 0x94, 0x4e, 0x17, 0x73, 0x44, 0xa9, 0x86, 0x79, 0x0b, 0xd5, 0xa5,
	0x2e, 0x17, 0x8a, 0x68, 0xee, 0xfc, 0xb7, 0x3b, 0xeb, 0x2d, 0x76, 0xe1, 0x44, 0x7d, 0x57, 0x77,
	0x32, 0x30, 0xfe, 0xf8, 0x6d, 0xe4, 0x11, 0xfd, 0x6c, 0x74, 0x6d, 0xb5, 0xcd, 0xe6, 0x4e, 0x7b,
	0x76, 0x64, 0xf9, 0xba, 0x6c, 0xb0, 0x8d, 0xc1, 0xaf, 0xa3, 0x73, 0x55, 0xf5, 0x24, 0xc9, 0x58,
	0x6e, 0x86, 0x3f, 0x58, 0x29, 0xb5, 0xbb, 0x5a, 0xa9, 0x5b, 0x55, 0x76, 0xc1, 0x78, 0xc1, 0x50,
	0x07, 0x2d, 0xab, 0x34, 0x4e, 0x5b, 0x08, 0x97, 0x4e, 0x05, 0x8d, 0x99, 0x60, 0x34, 0x57, 0xd2,
	0xf7, 0x36, 0x6a, 0x9b, 0x8d, 0xe0, 0xa2, 0xb5, 0x04, 0x95, 0x01, 0x8f, 0x27, 0xee, 0x82, 0x8c,
	0xf9, 0x48, 0x85, 0x31, 0x11, 0xfe, 0x12, 0x1c, 0xe2, 0x6a, 0xd7, 0xce, 0x82, 0xe6, 0x90, 0xae,
	0xe5, 0x90, 0xee, 0x1e, 0x67, 0x79, 0xff, 0xa6, 0xae, 0xff, 0xbb, 0xdf, 0xd6, 0x37, 0x8f, 0x99,
	0x1a, 0x8e, 0xa2, 0x6e, 0xcc, 0x33, 0x4b, 0x3f, 0xf6, 0xcf, 0x96, 0x4c, 0x1e, 0xf6, 0xd4, 0x58,
	0x50, 0x09, 0x01, 0x32, 0xb8, 0x60, 0xd3, 0x1c, 0x40, 0x96, 0x3d, 0x22, 0xf0, 0x0d, 0x74, 0x51,
	0x0a, 0x9e, 0x4b, 0x5e, 0xd0, 0x24, 0x94, 0x34, 0x4f, 0x68, 0x21, 0xfd, 0x65, 0x28, 0xf4, 0x42,
	0x65, 0x38, 0x34, 0x7a, 0x7c, 0x0b, 0x5d, 0x9e, 0x38, 0xa7, 0x24, 0xa7, 0xa1, 0xe6, 0x09, 0x7d,
	0x83, 0x0d, 0xb8, 0xc1, 0xff, 0x54, 0xd6, 0xf7, 0x49, 0x4e, 0x1f, 0x90, 0x53, 0x7d, 0x9d, 0xf7,
	0xd0, 0xc6, 0x64, 0xb6, 0xec, 0xf1, 0x58, 0xae, 0x68, 0x71, 0x42, 0xd2, 0x30, 0x4a, 0x79, 0xfc,
	0xd0, 0x8c, 0x6c, 0x2d, 0xf8, 0x7f, 0xe5, 0x67, 0xea, 0xdb, 0xb7, 0x5e, 0x7d, 0x70, 0xc2, 0x6f,
	0xa0, 0xf3, 0xe6, 0x29, 0xc8, 0xb0, 0xa4, 0xbf, 0x26, 0xd0, 0xdf, 0x39, 0xab, 0xbe, 0x63, 0xb4,
	0xf8, 0x06, 0xc2, 0xba, 0x2e, 0xcd, 0x13, 0xe4, 0x98, 0x96, 0x39, 0x5a, 0x90, 0xe3, 0x7c, 0x46,
	0x4e, 0x07, 0x24, 0xda, 0x3d, 0xa6, 0x06, 0xf5, 0xf6, 0xda, 0x57, 0x2f, 0x1e, 0x5f, 0xbf, 0x04,
	0x83, 0xd2, 0x3b, 0x2d, 0xd7, 0x81, 0x19, 0xd1, 0xce, 0x99, 0x83, 0x6a, 0x03, 0x12, 0xe1, 0x4b,
	0x48, 0x3f, 0x94, 0x90, 0x25, 0x30, 0xa9, 0x6e, 0x50, 0x27, 0x42, 0xec, 0x27, 0x9a, 0x9d, 0x85,
	0xee, 0x26, 0x0c, 0x6a, 0x23, 0x30, 0x42, 0xa9, 0xb5, 0x0c, 0x6c, 0xb4, 0x74, 0xc2, 0xe4, 0xee,
	0x34, 0x93, 0xef, 0x21, 0x8f, 0x64, 0x7c, 0x94, 0xab, 0x79, 0xa8, 0xd1, 0x86, 0xea, 0x89, 0xe4,
	0x82, 0xe6, 0x34, 0x09, 0x87, 0x86, 0xb4, 0x3c, 0x38, 0x69, 0xcb, 0x28, 0xef, 0x83, 0xce, 0xec,
	0x0c, 0x55, 0x30, 0x2a, 0x81, 0xd3, 0xdc, 0xa0, 0x14, 0x3b, 0xdf, 0x38, 0xa8, 0xb5, 0x2b, 0xc4,
	0x6e, 0x9a, 0xf2, 0x47, 0x24, 0x8f, 0xa1, 0x54, 0xfe, 0x28, 0xa7, 0x45, 0xb9, 0x74, 0x40, 0x98,
	0xea, 0xc1, 0xe2, 0x5f, 0x7a, 0x60, 0xce, 0x55, 0x9b, 0x7d, 0x2e, 0x77, 0xee, 0x73, 0x75, 0x3e,
	0x47, 0x8d, 0xbd, 0x94, 0xb0, 0x4c, 0x5f, 0xea, 0xdf, 0x5c, 0x81, 0x49, 0xbf, 0x38, 0x3b, 0x7d,
	0x6d, 0xfe, 0xf4, 0x9f, 0xa1, 0xe6, 0x01, 0xe7, 0x69, 0x9f, 0xa4, 0xd0, 0x15, 0x8c, 0x5c, 0xc1,
	0x79, 0x6a, 0x9b, 0x02, 0xdf, 0xff, 0xcd, 0xec, 0x3f, 0x3a, 0xc8, 0x1b, 0x70, 0x45, 0x52, 0xf9,
	0x92, 0x1f, 0x01, 0x7b, 0xc8, 0x3b, 0xe1, 0xe9, 0x28, 0xa3, 0xfe, 0xe2, 0x1c, 0x59, 0x4c, 0x28,
	0x7e, 0x17, 0xb9, 0x47, 0x94, 0xca, 0x79, 0x0a, 0x85, 0x40, 0xbd, 0x77, 0x04, 0x19, 0x67, 0x40,
	0x6f, 0x2e, 0x5c, 0x4c, 0x25, 0x77, 0xfe, 0x70, 0x51, 0xeb, 0x1e, 0xcd, 0xa9, 0x64, 0xf2, 0x50,
	0x11, 0xa5, 0xb3, 0x79, 0x02, 0x1e, 0x16, 0x9c, 0xa4, 0xb9, 0xf3, 0xbf, 0xd9, 0xfc, 0x6c, 0x1e,
	0x5f, 0xbf, 0xa1, 0xab, 0xf9, 0xf6, 0xc5, 0xe3, 0xeb, 0x4e, 0x60, 0xc3, 0xf0, 0x1d, 0x84, 0xe2,
	0x72, 0x22, 0xf4, 0x8e, 0xd2, 0xfc, 0xb8, 0x3e, 0x1b, 0xa4, 0x9a, 0x1c, 0xcb, 0xf2, 0x53, 0x81,
	0xf8, 0x1d, 0x54, 0xd7, 0xd7, 0x57, 0xae, 0x89, 0x6b, 0x2f, 0x29, 0x63, 0x72, 0xf9, 0xe5, 0x9a,
	0x81, 0x28, 0x7c, 0x0b, 0xb9, 0x8a, 0x44, 0xfa, 0xbc, 0x86, 0x9f, 0x67, 0x46, 0x0f, 0x48, 0x64,
	0xa3, 0xc0, 0x19, 0xdf, 0x47, 0x88, 0x94, 0x2f, 0x4c, 0xfa, 0x75, 0x08, 0xed, 0xcc, 0x0e, 0x9d,
	0x7e, 0x8c, 0x65, 0xf5, 0x93, 0x58, 0x7c, 0x1b, 0x79, 0x0a, 0x06, 0x03, 0xf6, 0xc9, 0x4b, 0xbb,
	0x68, 0x86, 0xa7, 0xdc, 0x71, 0x26, 0x02, 0x07, 0xa8, 0xe4, 0xca, 0x30, 0xd3, 0x1c, 0x9c, 0xcc,
	0xf3, 0x03, 0x67, 0xc5, 0x42, 0x3c, 0x00, 0x04, 0xfc, 0x85, 0x83, 0xd6, 0x26, 0xdb, 0x8b, 0x25,
	0xa1, 0x1a, 0x32, 0x59, 0x31, 0xbc, 0xbf, 0x6c, 0xbb, 0xf4, 0x0f, 0x6e, 0xb1, 0x2b, 0xd5, 0x16,
	0x63, 0xc9, 0x60, 0xc8, 0x64, 0xb5, 0x27, 0x3e, 0x7c, 0x72, 0xd6, 0x76, 0x9e, 0x9e, 0xb5, 0x9d,
	0xdf, 0xcf, 0xda, 0xce, 0xd7, 0xcf, 0xdb, 0x0b, 0x4f, 0x9f, 0xb7, 0x17, 0x7e, 0x79, 0xde, 0x5e,
	0xf8, 0xf8, 0xcd, 0x29, 0xf0, 0x6c, 0xa4, 0x86, 0xa3, 0x9d, 0x9d, 0x9b, 0xdb, 0x3d, 0x68, 0xdc,
	0x96, 0xf9, 0x47, 0xc0, 0x7c, 0x56, 0x1b, 0x00, 0xf2, 0x45, 0x1e, 0xfc, 0x26, 0xbf, 0xf5, 0xe7,
	0x00, 0x70, 0xca, 0x80, 0x9c, 0x32, 0x0c, 0x00, 0x00,
}

func (m *FeeAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Decimals != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x4a
	}
	{
		size := m.CreditPrice.Size()
		i -= size
		if _, err := m.CreditPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.QuotaWeight.Size()
		i -= size
		if _, err := m.QuotaWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.TabSettleThreshold.Size()
		i -= size
		if _, err := m.TabSettleThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MicroThreshold.Size()
		i -= size
		if _, err := m.MicroThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MaxFee.Size()
		i -= size
		if _, err := m.MaxFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinFee.Size()
		i -= size
		if _, err := m.MinFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Split) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Split) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Split) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TreasuryBps != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.TreasuryBps))
		i--
		dAtA[i] = 0x20
	}
	if m.RelayerBps != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.RelayerBps))
		i--
		dAtA[i] = 0x18
	}
	if m.ValidatorBps != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.ValidatorBps))
		i--
		dAtA[i] = 0x10
	}
	if m.AppBps != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.AppBps))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTabAgeBlocks != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.MaxTabAgeBlocks))
		i--
		dAtA[i] = 0x60
	}
	if m.CreditsEnabled {
		i--
		if m.CreditsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.ValidatorPayoutIntervalBlocks != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.ValidatorPayoutIntervalBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.SponsoredLaneMaxBps != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.SponsoredLaneMaxBps))
		i--
		dAtA[i] = 0x48
	}
	if len(m.SponsoredSenders) > 0 {
		for iNdEx := len(m.SponsoredSenders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SponsoredSenders[iNdEx])
			copy(dAtA[i:], m.SponsoredSenders[iNdEx])
			i = encodeVarintSettle(dAtA, i, uint64(len(m.SponsoredSenders[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.RelayerPayoutCap) > 0 {
		for iNdEx := len(m.RelayerPayoutCap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RelayerPayoutCap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.RelayerRecipients) > 0 {
		for iNdEx := len(m.RelayerRecipients) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RelayerRecipients[iNdEx])
			copy(dAtA[i:], m.RelayerRecipients[iNdEx])
			i = encodeVarintSettle(dAtA, i, uint64(len(m.RelayerRecipients[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RelayerAdmin) > 0 {
		i -= len(m.RelayerAdmin)
		copy(dAtA[i:], m.RelayerAdmin)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.RelayerAdmin)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TreasuryAdmin) > 0 {
		i -= len(m.TreasuryAdmin)
		copy(dAtA[i:], m.TreasuryAdmin)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.TreasuryAdmin)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Split.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.FeeBps != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.FeeBps))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Tab) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tab) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tab) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Entries != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.Entries))
		i--
		dAtA[i] = 0x38
	}
	if m.OpenedHeight != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.OpenedHeight))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Payee) > 0 {
		i -= len(m.Payee)
		copy(dAtA[i:], m.Payee)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Payee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Payer) > 0 {
		i -= len(m.Payer)
		copy(dAtA[i:], m.Payer)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Payer)))
		i--
		dAtA[i] = 0x12
	}
	if m.AppId != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AppAllowance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppAllowance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppAllowance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AppId != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Claimable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Claimable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Claimable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.AppId != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoolBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pool) > 0 {
		i -= len(m.Pool)
		copy(dAtA[i:], m.Pool)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Pool)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Totals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Totals) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Totals) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Payments != 0 {
		i = encodeVarintSettle(dAtA, i, uint64(m.Payments))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Fees.Size()
		i -= size
		if _, err := m.Fees.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Volume.Size()
		i -= size
		if _, err := m.Volume.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintSettle(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayerPaidThisInterval) > 0 {
		for iNdEx := len(m.RelayerPaidThisInterval) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RelayerPaidThisInterval[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.CreditsMinted.Size()
		i -= size
		if _, err := m.CreditsMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Totals) > 0 {
		for iNdEx := len(m.Totals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Totals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Allowances) > 0 {
		for iNdEx := len(m.Allowances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Allowances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Tabs) > 0 {
		for iNdEx := len(m.Tabs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tabs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Claimables) > 0 {
		for iNdEx := len(m.Claimables) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claimables[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSettle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintSettle(dAtA []byte, offset int, v uint64) int {
	offset -= sovSettle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	l = m.MinFee.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = m.MaxFee.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = m.MicroThreshold.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = m.TabSettleThreshold.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = m.QuotaWeight.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = m.CreditPrice.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovSettle(uint64(m.Decimals))
	}
	return n
}

func (m *Split) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppBps != 0 {
		n += 1 + sovSettle(uint64(m.AppBps))
	}
	if m.ValidatorBps != 0 {
		n += 1 + sovSettle(uint64(m.ValidatorBps))
	}
	if m.RelayerBps != 0 {
		n += 1 + sovSettle(uint64(m.RelayerBps))
	}
	if m.TreasuryBps != 0 {
		n += 1 + sovSettle(uint64(m.TreasuryBps))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FeeBps != 0 {
		n += 1 + sovSettle(uint64(m.FeeBps))
	}
	l = m.Split.Size()
	n += 1 + l + sovSettle(uint64(l))
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	l = len(m.TreasuryAdmin)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = len(m.RelayerAdmin)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	if len(m.RelayerRecipients) > 0 {
		for _, s := range m.RelayerRecipients {
			l = len(s)
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if len(m.RelayerPayoutCap) > 0 {
		for _, e := range m.RelayerPayoutCap {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if len(m.SponsoredSenders) > 0 {
		for _, s := range m.SponsoredSenders {
			l = len(s)
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if m.SponsoredLaneMaxBps != 0 {
		n += 1 + sovSettle(uint64(m.SponsoredLaneMaxBps))
	}
	if m.ValidatorPayoutIntervalBlocks != 0 {
		n += 1 + sovSettle(uint64(m.ValidatorPayoutIntervalBlocks))
	}
	if m.CreditsEnabled {
		n += 2
	}
	if m.MaxTabAgeBlocks != 0 {
		n += 1 + sovSettle(uint64(m.MaxTabAgeBlocks))
	}
	return n
}

func (m *Tab) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovSettle(uint64(m.AppId))
	}
	l = len(m.Payer)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = len(m.Payee)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovSettle(uint64(l))
	if m.OpenedHeight != 0 {
		n += 1 + sovSettle(uint64(m.OpenedHeight))
	}
	if m.Entries != 0 {
		n += 1 + sovSettle(uint64(m.Entries))
	}
	return n
}

func (m *AppAllowance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	if m.AppId != 0 {
		n += 1 + sovSettle(uint64(m.AppId))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovSettle(uint64(l))
	return n
}

func (m *Claimable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovSettle(uint64(m.AppId))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovSettle(uint64(l))
	return n
}

func (m *PoolBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pool)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovSettle(uint64(l))
	return n
}

func (m *Totals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovSettle(uint64(l))
	}
	l = m.Volume.Size()
	n += 1 + l + sovSettle(uint64(l))
	l = m.Fees.Size()
	n += 1 + l + sovSettle(uint64(l))
	if m.Payments != 0 {
		n += 1 + sovSettle(uint64(m.Payments))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovSettle(uint64(l))
	if len(m.Claimables) > 0 {
		for _, e := range m.Claimables {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if len(m.Tabs) > 0 {
		for _, e := range m.Tabs {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if len(m.Allowances) > 0 {
		for _, e := range m.Allowances {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	if len(m.Totals) > 0 {
		for _, e := range m.Totals {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	l = m.CreditsMinted.Size()
	n += 1 + l + sovSettle(uint64(l))
	if len(m.RelayerPaidThisInterval) > 0 {
		for _, e := range m.RelayerPaidThisInterval {
			l = e.Size()
			n += 1 + l + sovSettle(uint64(l))
		}
	}
	return n
}

func sovSettle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSettle(x uint64) (n int) {
	return sovSettle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MicroThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MicroThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TabSettleThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TabSettleThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QuotaWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreditPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Split) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Split: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Split: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppBps", wireType)
			}
			m.AppBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorBps", wireType)
			}
			m.ValidatorBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerBps", wireType)
			}
			m.RelayerBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayerBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryBps", wireType)
			}
			m.TreasuryBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreasuryBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBps", wireType)
			}
			m.FeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Split", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Split.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, FeeAsset{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerRecipients", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerRecipients = append(m.RelayerRecipients, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerPayoutCap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerPayoutCap = append(m.RelayerPayoutCap, types.Coin{})
			if err := m.RelayerPayoutCap[len(m.RelayerPayoutCap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SponsoredSenders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SponsoredSenders = append(m.SponsoredSenders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SponsoredLaneMaxBps", wireType)
			}
			m.SponsoredLaneMaxBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SponsoredLaneMaxBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPayoutIntervalBlocks", wireType)
			}
			m.ValidatorPayoutIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorPayoutIntervalBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CreditsEnabled = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTabAgeBlocks", wireType)
			}
			m.MaxTabAgeBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTabAgeBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tab) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tab: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tab: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenedHeight", wireType)
			}
			m.OpenedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpenedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			m.Entries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Entries |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppAllowance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppAllowance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppAllowance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Claimable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Claimable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Claimable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pool", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pool = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Totals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Totals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Totals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Volume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payments", wireType)
			}
			m.Payments = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Payments |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimables = append(m.Claimables, Claimable{})
			if err := m.Claimables[len(m.Claimables)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, PoolBalance{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tabs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tabs = append(m.Tabs, Tab{})
			if err := m.Tabs[len(m.Tabs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allowances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Allowances = append(m.Allowances, AppAllowance{})
			if err := m.Allowances[len(m.Allowances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Totals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Totals = append(m.Totals, Totals{})
			if err := m.Totals[len(m.Totals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditsMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreditsMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerPaidThisInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerPaidThisInterval = append(m.RelayerPaidThisInterval, types.Coin{})
			if err := m.RelayerPaidThisInterval[len(m.RelayerPaidThisInterval)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSettle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSettle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSettle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSettle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSettle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSettle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSettle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSettle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSettle = fmt.Errorf("proto: unexpected end of group")
)
