# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 VaporChain / muthu2201
# Provenance: VAPOR-6eabb1be532bdef4
# Example scrape config; merge into your prometheus.yml.
global:
  scrape_interval: 15s
rule_files:
  - vaporchain.rules.yml
scrape_configs:
  - job_name: vaporchain-node
    static_configs: [{ targets: ["node0:26660", "node1:26660"] }]
  - job_name: vapor-sponsor
    static_configs: [{ targets: ["sponsor:9800"] }]
  - job_name: vapor-indexer
    static_configs: [{ targets: ["indexer:9900"] }]
