// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 VaporChain / muthu2201
// Provenance: VAPOR-6eabb1be532bdef4
//
// Generates typed `as const` ABIs for the SDK from Foundry artifacts and the
// Settle precompile ABI (single source of truth: chain/precompiles/settle).
import { readFileSync, writeFileSync } from 'node:fs'

const header = `// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 VaporChain / muthu2201
// Provenance: VAPOR-6eabb1be532bdef4
// AUTO-GENERATED by scripts/gen-abis.mjs — do not edit by hand.
`
const out = 'packages/sdk/src/abi'
const art = (p) => JSON.parse(readFileSync(`contracts/out/${p}`, 'utf8')).abi
const items = {
  settleAbi: JSON.parse(readFileSync('chain/precompiles/settle/abi.json', 'utf8')),
  vaporCheckoutAbi: art('VaporCheckout.sol/VaporCheckout.json'),
  vaporTokenFactoryAbi: art('VaporTokenFactory.sol/VaporTokenFactory.json'),
  vaporTokenAbi: art('VaporToken.sol/VaporToken.json'),
  verifyingPaymasterAbi: art('VaporVerifyingPaymaster.sol/VaporVerifyingPaymaster.json'),
  tokenPaymasterAbi: art('VaporTokenPaymaster.sol/VaporTokenPaymaster.json'),
}
for (const [name, abi] of Object.entries(items)) {
  writeFileSync(`${out}/${name}.ts`, `${header}\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const\n`)
}
writeFileSync(`${out}/index.ts`, header + Object.keys(items).map((n) => `export { ${n} } from './${n}.js'`).join('\n') + '\n')
console.log('generated', Object.keys(items).join(', '))
